# Generated by Django 3.0.7 on 2020-06-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200623_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='pno',
        ),
    ]
