# Generated by Django 3.0.7 on 2020-06-25 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_myprofile_pno'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='pno',
            field=models.CharField(blank='True', default='True', max_length=10, validators=[django.core.validators.RegexValidator('^0?[5-9]d{1}\\d{9}$')]),
        ),
    ]
