# Generated by Django 3.0.7 on 2020-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_myprofile_pno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='pno',
            field=models.CharField(blank='True', max_length=10, null='True'),
        ),
    ]
