# Generated by Django 3.0.7 on 2020-06-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200625_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
