# Generated by Django 3.0.7 on 2020-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20200627_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='pic',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images//'),
        ),
    ]
